---
# defaults file for common

cluster_id: cluster-5
cluster_zone: europe-central2
gcp_project_id: curious-furnace-316611

service_account_key_file: "{{ lookup('env', 'GOOGLE_APPLICATION_CREDENTIALS') }}"