---
# defaults file for common
service_account_key_file: "{{ lookup('env', 'GOOGLE_APPLICATION_CREDENTIALS') }}"

cluster_id: cluster-5
cluster_zone: europe-central2
gcp_project_id: curious-furnace-316611