---
# tasks file for dns
- name: Get Ingress Controller external IP
  shell:
    set -o errexit
    set -o pipefail
    set -o nounset

      kubectl describe service {{ ingress_nginx_controller }} -n  {{ cert_manager_name_space }} |
       grep "LoadBalancer Ingress:" |
       awk '{print $3;}'

    exit 0
  run_once: True
  changed_when: False
  register: result
  args:
    executable: "/bin/bash"

- set_fact:
    ingress_controller_ip: "{{ result.stdout_lines[0] }}"

#- name: Create a managed zone
#  google.cloud.gcp_dns_managed_zone:
#    name: mambuzone
#    description: test zone
#    dns_name: automambu.com.
#    project: "{{ gcp_project }}"
#    auth_kind: "{{ gcp_cred_kind }}"
#    service_account_file: "{{ gcp_cred_file }}"
#    state: present
#  register: managed_zone

- name: Create juice shop record set
  google.cloud.gcp_dns_resource_record_set:
    name: "{{ juice_shop_dns }}."
    managed_zone: "{{ zone_name }}"
    type: A
    ttl: 600
    target:
    - "{{ ingress_controller_ip }}"
    project:  "{{ gcp_project }}"
    auth_kind: serviceaccount
    service_account_file: "{{ gcp_cred_file }}"
    state: present

- name: Create grafana record set
  google.cloud.gcp_dns_resource_record_set:
    name: "{{ grafana_dns }}."
    managed_zone: "{{ zone_name }}"
    type: A
    ttl: 600
    target:
    - "{{ ingress_controller_ip }}"
    project:  "{{ gcp_project }}"
    auth_kind: serviceaccount
    service_account_file: "{{ gcp_cred_file }}"
    state: present

- set_fact:
    juice_shop_dns : "{{ juice_shop_dns }}"

- set_fact:
    grafana_dns : "{{ grafana_dns }}"