# Helm chart version
cert_manager_chart_version: "v1.3.1"

# Helm release name
cert_manager_release_name: "cert-manager"

# Helm repository name
cert_manager_repo_name: "jetstack"

# Helm chart name
cert_manager_chart_name: "{{ cert_manager_repo_name }}/{{ cert_manager_release_name }}"

# Helm chart URL
cert_manager_chart_url: "https://charts.jetstack.io"

# Kubernetes namespace where cert-manager resources should be installed
cert_manager_namespace: "cert-manager"

# The following table contains the configurable parameters of the cert-manager
cert_manager_values:
   installCRDs: true
   prometheus.servicemonitor.enabled: true