---
# tasks file for juice-shop
- name: Git clone stable repo on HEAD
  ansible.builtin.git:
    repo: "{{ juice_shop_repo_url }}"
    dest: "{{ juice_shop_clone_repo }}"

- name: Deploy Grafana chart from local path
  kubernetes.core.helm:
    name: "{{ juice_shop_release_name }}"
    chart_ref: "{{ juice_shop_clone_repo }}"
    release_namespace:  "{{ juice_shop_namespace }}"
    create_namespace: true
    values:  "{{ lookup('template', 'templates/values.yaml') | from_yaml }}"