---
- name: Add cert-manager repo
  kubernetes.core.helm_repository:
    name:  "{{ cert_manager_repo_name }}"
    repo_url:  "{{ cert_manager_chart_url }}"

- name: Deploy cert-manager
  kubernetes.core.helm:
    name: "{{ cert_manager_release_name }}"
    chart_ref: "{{ cert_manager_chart_name }}"
    release_namespace: "{{ cert_manager_namespace }}"
    create_namespace: true
    wait: yes
    values: "{{ cert_manager_values }}"