---
# defaults file for prometheus

# Helm chart version
prometheus_chart_version: "v1.3.1"

# Helm release name
prometheus_release_name: "prometheus"

# Helm repository name
prometheus_repo_name: "prometheus-community"

# Helm chart name
prometheus_chart_name: "{{ prometheus_repo_name }}/{{ prometheus_release_name }}"

# Helm chart URL
prometheus_chart_url: "https://prometheus-community.github.io/helm-charts"

# Kubernetes namespace where prometheus resources should be installed
prometheus_namespace: "monitoring"

# The following table contains the configurable parameters of the prometheus
prometheus_values:
   server.persistentVolume.size: 20Gi
   server.retention: 10d